import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { DashboardPreferencesService } from '../core/dashboard-preferences.service';
import { InspectionService } from '../core/inspection.service';
import { McpKey } from '../models';
import { HeaderComponent } from '../shared/header.component';

@Component({ imports: [ReactiveFormsModule, RouterLink, HeaderComponent], template: `<main><app-header /><nav><a routerLink="/home">← Home</a></nav><section class="card"><h2>Dashboard preferences</h2><label class="toggle"><input type="checkbox" [checked]="preferences.value().showDescription" (change)="preferences.update({showDescription: $any($event.target).checked})"> Show descriptions</label><label class="toggle"><input type="checkbox" [checked]="preferences.value().showTaskPreview" (change)="preferences.update({showTaskPreview: $any($event.target).checked})"> Show task preview</label><label>Preview count<select [value]="preferences.value().previewCount" (change)="setPreview($any($event.target).value)"><option value="0">Off</option><option value="3">3</option><option value="5">5</option><option value="10">10</option></select></label><label class="toggle"><input type="checkbox" [checked]="preferences.value().showLatestActivity" (change)="preferences.update({showLatestActivity: $any($event.target).checked})"> Show latest activity</label><label class="toggle"><input type="checkbox" [checked]="preferences.value().showRecentNote" (change)="preferences.update({showRecentNote: $any($event.target).checked})"> Show recent note</label><label class="toggle"><input type="checkbox" [checked]="preferences.value().showArchived" (change)="preferences.update({showArchived: $any($event.target).checked})"> Show archived projects</label></section><section class="card"><h2>MCP keys</h2>@if (error()) { <p class="error">{{ error() }}</p> }@if (secret()) { <p class="secret"><strong>Copy now; this is shown once:</strong><code>{{ secret() }}</code></p> }@if (!inspection.active()) { <form class="inline" [formGroup]="form" (ngSubmit)="create()"><input formControlName="name" placeholder="Key name" required><button>Create key</button></form> }@for (key of keys(); track key.id) { <p>{{ key.name }} @if (key.revoked_at) { <small>Revoked</small> } @else if (!inspection.active()) { <button class="link danger" (click)="revoke(key.id)">Revoke</button> }</p> }</section></main>` })
export class AccountComponent {
  private api = inject(ApiService); readonly inspection = inject(InspectionService); readonly preferences = inject(DashboardPreferencesService); readonly keys = signal<McpKey[]>([]); readonly secret = signal(''); readonly error = signal('');
  readonly form = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: Validators.required }) });
  constructor() { void this.load(); } setPreview(value: string) { this.preferences.update({ previewCount: Number(value) as 0 | 3 | 5 | 10 }); }
  async load() { try { this.keys.set(await this.api.request<McpKey[]>('/api/mcp-keys')); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
  async create() { if (this.inspection.active() || this.form.invalid) return; try { const key = await this.api.request<McpKey & { secret: string }>('/api/mcp-keys', { method: 'POST', body: this.form.getRawValue() }); this.secret.set(key.secret); this.form.reset({ name: '' }); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
  async revoke(id: number) { if (!this.inspection.active()) { try { await this.api.request(`/api/mcp-keys/${id}`, { method: 'DELETE' }); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } } }
}
