import { Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { InspectionService } from '../core/inspection.service';
import { User } from '../models';
import { HeaderComponent } from '../shared/header.component';

@Component({ imports: [ReactiveFormsModule, RouterLink, HeaderComponent], template: `<main><app-header /><nav><a routerLink="/home">← Home</a><a routerLink="/account">Account</a></nav><section class="card"><h2>Users</h2>@if (error()) { <p class="error">{{ error() }}</p> }@if (!inspection.active()) { <form [formGroup]="form" (ngSubmit)="create()" novalidate><p class="form-error" [class.visible]="submitted() && form.invalid">Please correct the highlighted fields before creating the user.</p><label>Username<input formControlName="username" aria-describedby="username-help"></label><small id="username-help" class="form-help">Use 3–64 lowercase characters: start with a letter, then letters, numbers, periods, underscores, or hyphens.</small>@if (form.controls.username.touched && form.controls.username.invalid) { <p class="field-error">Enter a valid username.</p> }<label>Display name<input formControlName="display_name" aria-describedby="display-name-help"></label><small id="display-name-help" class="form-help">A display name is required.</small>@if (form.controls.display_name.touched && form.controls.display_name.invalid) { <p class="field-error">Enter a display name.</p> }<label>Temporary password<input formControlName="temporary_password" type="password" aria-describedby="password-help"></label><small id="password-help" class="form-help">Temporary password must be at least 12 characters.</small>@if (form.controls.temporary_password.touched && form.controls.temporary_password.invalid) { <p class="field-error">Enter a temporary password with at least 12 characters.</p> }<label><input formControlName="is_admin" type="checkbox"> Administrator</label><button>Create user</button></form> }@for (user of users(); track user.id) { <p><strong>{{ user.display_name }}</strong> @{{ user.username }} {{ user.active ? '' : '(inactive)' }}@if (user.active && !inspection.active()) { <button class="link" (click)="reset(user.id)">Reset password</button><button class="link danger" (click)="deactivate(user.id)">Deactivate</button> }</p> }</section></main>` })
export class AdminComponent {
  private api = inject(ApiService); readonly inspection = inject(InspectionService); readonly users = signal<User[]>([]); readonly error = signal(''); readonly submitted = signal(false);
  readonly form = new FormGroup({ username: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.pattern(/^[a-z][a-z0-9._-]{2,63}$/)] }), display_name: new FormControl('', { nonNullable: true, validators: Validators.required }), temporary_password: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(12)] }), is_admin: new FormControl(false, { nonNullable: true }) });
  constructor() { void this.load(); }
  async load() { try { this.users.set(await this.api.request<User[]>('/api/users')); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
  async create() { this.form.controls.username.setValue(this.form.controls.username.value.trim().toLowerCase()); this.submitted.set(true); this.form.markAllAsTouched(); if (this.inspection.active() || this.form.invalid) return; try { await this.api.request('/api/users', { method: 'POST', body: this.form.getRawValue() }); this.form.reset({ username: '', display_name: '', temporary_password: '', is_admin: false }); this.submitted.set(false); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
  async reset(id: number) { if (this.inspection.active()) return; const temporary_password = prompt('New temporary password (12+ characters)'); if (temporary_password && temporary_password.length >= 12) try { await this.api.request(`/api/users/${id}/reset-password`, { method: 'POST', body: { temporary_password } }); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
  async deactivate(id: number) { if (!this.inspection.active()) try { await this.api.request(`/api/users/${id}/deactivate`, { method: 'POST' }); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : String(error)); } }
}
