import { Component, computed, effect, ElementRef, HostListener, inject, signal, viewChild } from '@angular/core';
import { NgStyle } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService } from '../core/api.service';
import { InspectionService } from '../core/inspection.service';
import { Member, Person, Project, Tag, Task } from '../models';
import { HeaderComponent } from '../shared/header.component';
import { TaskFilterBarComponent } from '../shared/task-filter-bar.component';
import { defaultTaskFilter, filterTasks, TaskFilter } from '../shared/task-filters';
import { TagCreateRequest, TaskFormComponent, taskForm } from '../shared/task-form.component';
import { TaskTableComponent } from '../shared/task-table.component';
import { tagStyle } from '../shared/tag-colors';
import { RelativeTimePipe } from '../shared/relative-time.pipe';

@Component({ imports: [NgStyle, ReactiveFormsModule, HeaderComponent, TaskFilterBarComponent, TaskTableComponent, TaskFormComponent, RelativeTimePipe], template: `
<main><app-header /><p class="error">{{ error() }}</p><header class="page-title"><h2 tabindex="-1">{{ project()?.name }}</h2>@if (writable()) { <button (click)="openNew()">New task</button> }</header>
@if (project()?.tasks_enabled) { <app-task-filter-bar [tags]="tags()" [state]="filter()" (apply)="apply($event)" (resetFilters)="reset()" /><app-task-table [tasks]="visible()" (open)="open($event)" (tagClick)="filterTag($event)" /> }
@if (creating()) { <dialog #newTaskDialog class="modal" aria-label="New task" (cancel)="closeNew($event)"><button class="close" aria-label="Close new task" (click)="closeNew()">×</button><h2>New task</h2><form (ngSubmit)="createTask()"><app-task-form [form]="newTask" [tags]="tags()" [members]="assignees()" [manageTagsUrl]="tagUrl()" (tagCreate)="createTag($event)" /><button type="button" [disabled]="newTask.invalid" (click)="createTask()">Create task</button><button type="button" class="quiet" (click)="closeNew()">Cancel</button></form></dialog> }
@if (selected()) { <dialog #taskDrawer class="drawer" aria-label="Task details" (cancel)="close($event)"><button class="close" aria-label="Close task details" (click)="close()">×</button>@if (mode() === 'read') { <header class="task-drawer-header"><h2>{{ selected()!.title }}</h2><small>Task #{{ selected()!.id }} · {{ selected()!.target_project }}</small></header><div class="task-drawer-badges"><span>{{ selected()!.status }}</span><span>{{ selected()!.priority }}</span><span>{{ selected()!.assignee || 'Unassigned' }}</span></div>@if (selected()!.tags.length) { <div class="task-drawer-tags" aria-label="Tags">@for (tag of selected()!.tags; track tag.id) { <span class="tag-chip" [ngStyle]="style(tag.color)"><i aria-hidden="true"></i>{{ tag.name }}</span> }</div> }<section class="task-drawer-description"><h3>Description</h3><p>{{ selected()!.description || 'No description' }}</p></section><p class="task-drawer-times">Created by {{ selected()!.creator || 'Unknown' }} <time [attr.datetime]="selected()!.created_at" [title]="selected()!.created_at">{{ selected()!.created_at | relativeTime }}</time> · Updated <time [attr.datetime]="selected()!.updated_at" [title]="selected()!.updated_at">{{ selected()!.updated_at | relativeTime }}</time></p>@if (canModify()) { <footer class="task-drawer-actions"><button (click)="edit()">Edit</button><button (click)="mode.set('complete')">Complete</button><button class="danger" (click)="deleteTask()">Delete</button></footer> } } @else if (mode() === 'edit') { <h2>Edit task</h2><form (ngSubmit)="saveTask()"><app-task-form [form]="editTask" [tags]="tags()" [members]="assignees()" [projects]="projects()" [showProject]="true" [manageTagsUrl]="tagUrl(editTask.controls.target_project.value)" (targetChanged)="targetChanged()" (tagCreate)="createTag($event)" /><button [disabled]="editTask.invalid">Save</button><button type="button" class="quiet" (click)="cancelEdit()">Cancel</button></form> } @else { <h2>Complete task</h2><form [formGroup]="completeForm" (ngSubmit)="complete()"><label>Completion summary<textarea formControlName="summary" required></textarea></label><button [disabled]="completeForm.invalid">Complete</button><button type="button" class="quiet" (click)="cancelComplete()">Cancel</button></form> }</dialog> }
</main>` })
export class ProjectComponent {
  private api = inject(ApiService); private route = inject(ActivatedRoute); private router = inject(Router); private host = inject(ElementRef<HTMLElement>); readonly inspection = inject(InspectionService); readonly project = signal<Project | undefined>(undefined); readonly projects = signal<Project[]>([]); readonly tasks = signal<Task[]>([]); readonly tags = signal<Tag[]>([]); readonly members = signal<Member[]>([]); readonly directory = signal<Person[]>([]); readonly selected = signal<Task | undefined>(undefined); readonly creating = signal(false); readonly mode = signal<'read' | 'edit' | 'complete'>('read'); readonly error = signal(''); readonly filter = signal<TaskFilter>(defaultTaskFilter()); readonly taskDrawer = viewChild<ElementRef<HTMLDialogElement>>('taskDrawer'); readonly newTaskDialog = viewChild<ElementRef<HTMLDialogElement>>('newTaskDialog'); readonly newTask = taskForm(); readonly editTask = taskForm(); readonly completeForm = new FormGroup({ summary: new FormControl('', { nonNullable: true, validators: Validators.required }) }); private original = ''; private restoreIntent?: string; private loadGeneration = 0; private routeLoad?: string;
  readonly visible = computed(() => filterTasks(this.tasks(), this.filter()));
  constructor() { this.restoreIntent = this.router.getCurrentNavigation()?.extras.state?.['taskFocus'] as string | undefined; effect(() => { this.inspection.active(); this.loadRoute(); }); effect(() => this.syncDialogs()); this.route.paramMap.subscribe(() => this.loadRoute()); this.route.queryParamMap.subscribe(query => this.filter.set({ q: query.get('q') || '', project: this.key(), status: query.get('status') ?? 'TODO', priority: query.get('priority') || '', assignment: query.get('assignment') || 'all', sort: query.get('sort') || 'priority', tagIds: query.getAll('tag').map(Number).filter(Number.isInteger) })); }
  key() { return this.route.snapshot.paramMap.get('key')!; } writable() { return !!this.project()?.role && !this.project()?.archived && !this.inspection.active(); } canModify() { return this.writable() && this.selected()?.status === 'TODO'; } assignees() { return this.members().filter(member => this.directory().some(person => person.username === member.username)); } style(color: string) { return tagStyle(color); } tagUrl(key = this.key()) { return `/projects/${key}/tags`; }
  private loadRoute() { const route = `${this.key()}/${this.route.snapshot.paramMap.get('taskId') || ''}/${this.inspection.active()}`; if (route === this.routeLoad) return; this.routeLoad = route; void this.load(); }
  async load() { const generation = ++this.loadGeneration, key = this.key(), inspection = this.inspection.active(), taskId = this.route.snapshot.paramMap.get('taskId'), id = taskId === null ? NaN : Number(taskId); this.error.set(''); this.selected.set(undefined); try { const projects = await this.api.request<Project[]>(`/api/projects?inspection=${inspection}&include_archived=true`); if (generation !== this.loadGeneration) return; const project = projects.find(item => item.key === key); if (project && !project.tasks_enabled) { await this.router.navigateByUrl(`/projects/${key}/notes`, { replaceUrl: true }); return; } const [tasks, tags, directory, members] = await Promise.all([this.api.request<Task[]>(`/api/tasks?project=${encodeURIComponent(key)}&inspection=${inspection}`), this.api.request<Tag[]>(`/api/projects/${encodeURIComponent(key)}/tags?include_archived=true&inspection=${inspection}`), this.api.request<Person[]>('/api/directory'), project?.role ? this.api.request<Member[]>(`/api/projects/${key}/members`) : Promise.resolve([])]); if (generation !== this.loadGeneration) return; this.projects.set(projects); this.project.set(project); this.tasks.set(tasks); this.tags.set(tags); this.directory.set(directory); this.members.set(members); if (Number.isInteger(id)) await this.loadTask(id, key, inspection, generation); else this.focusAfterRender(generation); } catch (error) { if (generation === this.loadGeneration) this.error.set(error instanceof Error ? error.message : 'Request failed'); } }
  private async loadTask(id: number, key: string, inspection: boolean, generation: number) { try { const task = await this.api.request<Task>(`/api/tasks/${id}?inspection=${inspection}`); if (generation !== this.loadGeneration) return; if (task.target_project !== key) throw new Error('Task not found for this project.'); this.select(task); } catch { if (generation === this.loadGeneration) { this.error.set('Task not found for this project.'); this.selected.set(undefined); } } }
  private async loadTags(key: string) { this.tags.set(await this.api.request<Tag[]>(`/api/projects/${encodeURIComponent(key)}/tags?include_archived=true&inspection=${this.inspection.active()}`)); }
  private syncDialogs() { const drawer = this.taskDrawer()?.nativeElement; if (drawer) this.selected() ? drawer.open || drawer.showModal() : drawer.open && drawer.close(); const dialog = this.newTaskDialog()?.nativeElement; if (dialog) this.creating() ? dialog.open || dialog.showModal() : dialog.open && dialog.close(); }
  apply(filter: TaskFilter) { const state = { ...filter, project: this.key(), tagIds: [...filter.tagIds] }; this.filter.set(state); void this.router.navigate([], { relativeTo: this.route, queryParams: { q: state.q || null, status: state.status || null, priority: state.priority || null, assignment: state.assignment === 'all' ? null : state.assignment, sort: state.sort === 'priority' ? null : state.sort, tag: state.tagIds.length ? state.tagIds : null } }); }
  reset() { this.filter.set(defaultTaskFilter(this.key())); void this.router.navigate([], { relativeTo: this.route, queryParams: {} }); } filterTag(id: number) { this.apply({ ...this.filter(), tagIds: [id] }); } open(task: Task) { this.restoreIntent = `task-${task.id}`; return this.router.navigateByUrl(`/projects/${this.key()}/tasks/${task.id}`, { state: { taskFocus: this.restoreIntent } }); }
  openNew() { this.restoreIntent = 'new'; this.creating.set(true); } closeNew(event?: Event) { event?.preventDefault(); if (!this.discard()) return; this.creating.set(false); this.newTask.reset({ title: '', description: '', priority: 'NORMAL', target_project: this.key(), tag_ids: [], assigned_user: '' }); this.focusAfterRender(); }
  select(task: Task) { this.selected.set(task); this.mode.set('read'); this.editTask.reset({ title: task.title, description: task.description, priority: task.priority, target_project: task.target_project, tag_ids: task.tags.map(tag => tag.id), assigned_user: this.members().find(member => member.display_name === task.assignee)?.username || '' }); this.original = JSON.stringify(this.editTask.getRawValue()); this.editTask.markAsPristine(); this.completeForm.reset({ summary: '' }); }
  edit() { this.mode.set('edit'); } targetChanged() { this.editTask.controls.tag_ids.setValue([]); void this.loadTags(this.editTask.controls.target_project.value); } cancelEdit() { if (this.discard()) this.mode.set('read'); } cancelComplete() { if (this.discard()) this.mode.set('read'); }
  close(event?: Event) { event?.preventDefault(); if (!this.discard()) return; this.taskDrawer()?.nativeElement.close(); (this.host.nativeElement.querySelector('.page-title h2') as HTMLElement | null)?.focus(); this.selected.set(undefined); void this.router.navigateByUrl(`/projects/${this.key()}/tasks`, { state: { taskFocus: this.restoreIntent } }); }
  hasUnsavedChanges() { return (this.creating() && this.newTask.dirty) || (this.mode() === 'edit' && JSON.stringify(this.editTask.getRawValue()) !== this.original) || (this.mode() === 'complete' && this.completeForm.dirty); } canDeactivate() { return !this.hasUnsavedChanges() || confirm('Discard unsaved task changes?'); } @HostListener('window:beforeunload', ['$event']) beforeUnload(event: BeforeUnloadEvent) { if (this.hasUnsavedChanges()) { event.preventDefault(); event.returnValue = ''; } }
  private discard() { return !this.hasUnsavedChanges() || confirm('Discard unsaved task changes?'); } private focusAfterRender(generation = this.loadGeneration, attempt = 0) { if (!this.restoreIntent) return; requestAnimationFrame(() => { if (generation !== this.loadGeneration) return; const target = (this.host.nativeElement.querySelector(this.restoreIntent === 'new' ? '.page-title button' : `[data-task-id="${this.restoreIntent!.slice(5)}"]`) || this.host.nativeElement.querySelector('.page-title button, .page-title h2')) as HTMLElement | null; if (target && !this.host.nativeElement.querySelector('dialog[open]')) { target.focus(); this.restoreIntent = undefined; } else if (attempt < 30) this.focusAfterRender(generation, attempt + 1); else this.restoreIntent = undefined; }); }
  async createTag(request: TagCreateRequest) { try { const tag = await this.api.request<Tag>(`/api/projects/${this.editTask.controls.target_project.value || this.key()}/tags`, { method: 'POST', body: { name: request.name, color: request.color, description: request.description } }); this.tags.update(tags => [...tags, tag]); request.resolve(tag); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Request failed'); request.resolve(); } }
  async createTask() { if (this.newTask.invalid) return; await this.run(async () => { const { assigned_user, target_project, ...task } = this.newTask.getRawValue(), created = await this.api.request<Task>('/api/tasks', { method: 'POST', body: { ...task, target_project: this.key(), assigned_user: assigned_user || null } }); this.newTask.reset({ title: '', description: '', priority: 'NORMAL', target_project: this.key(), tag_ids: [], assigned_user: '' }); this.creating.set(false); this.restoreIntent = 'new'; await this.router.navigateByUrl(`/projects/${this.key()}/tasks/${created.id}`, { state: { taskFocus: this.restoreIntent } }); }, false); }
  async saveTask() { const task = this.selected(); if (!task || this.editTask.invalid) return; await this.run(async () => { const { assigned_user, ...patch } = this.editTask.getRawValue(); this.selected.set(await this.api.request<Task>(`/api/tasks/${task.id}`, { method: 'PATCH', body: { ...patch, assigned_user: assigned_user || null } })); this.original = JSON.stringify(this.editTask.getRawValue()); this.editTask.markAsPristine(); this.mode.set('read'); }); }
  async complete() { const task = this.selected(); if (!task || this.completeForm.invalid) return; await this.run(async () => { this.selected.set(await this.api.request<Task>(`/api/tasks/${task.id}/complete`, { method: 'POST', body: this.completeForm.getRawValue() })); this.completeForm.markAsPristine(); this.mode.set('read'); }); }
  async deleteTask() { const task = this.selected(); if (!task || !this.canModify() || !confirm(`Delete task “${task.title}”?`)) return; await this.run(async () => { await this.api.request(`/api/tasks/${task.id}`, { method: 'DELETE' }); await this.close(); }, false); } private async run(action: () => Promise<unknown>, reload = true) { try { await action(); if (reload) await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Request failed'); } }
}
