import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { InspectionService } from '../core/inspection.service';
import { Member, Person, Project } from '../models';
import { HeaderComponent } from '../shared/header.component';

@Component({ imports: [ReactiveFormsModule, RouterLink, HeaderComponent], template: `<main><app-header /><nav><a routerLink="/home">← Home</a><a [routerLink]="['/projects', key(), project()?.tasks_enabled ? 'tasks' : 'notes']">Project content</a></nav><h2>Project settings</h2><p class="error">{{ error() }}</p>@if (owner()) { <form class="card" [formGroup]="form" (ngSubmit)="save()"><label>Name<input formControlName="name" maxlength="120"></label><label>Description<textarea formControlName="description"></textarea></label><label>Color<input formControlName="color" type="color"></label><button type="button" class="quiet" (click)="form.controls.color.setValue(defaultColor)">Use default color</button><label class="toggle"><input formControlName="tasks_enabled" type="checkbox" [disabled]="project()!.todo_count + project()!.done_count > 0"> Tasks</label><label class="toggle"><input formControlName="notes_enabled" type="checkbox" [disabled]="project()!.note_count > 0"> Notes</label><small>Capabilities with existing content cannot be disabled.</small><button [disabled]="inspection.active() || form.invalid">Save settings</button><button type="button" class="danger" [disabled]="inspection.active()" (click)="archive()">{{ project()?.archived ? 'Unarchive' : 'Archive' }} project</button></form><section class="card"><h3>Members</h3>@for (member of members(); track member.username) { <p>{{ member.display_name }} — {{ member.role }} @if (member.role === 'MEMBER' && !inspection.active()) { <button class="link" (click)="transfer(member.username)">Transfer ownership</button><button class="link danger" (click)="remove(member.username)">Remove</button> }</p> }@if (!inspection.active()) { <form class="inline" [formGroup]="memberForm" (ngSubmit)="addMember()"><select formControlName="username"><option value="">Add member…</option>@for (person of available(); track person.username) { <option [value]="person.username">{{ person.display_name }}</option> }</select><button>Add</button></form> }</section> } @else { <p>Only the project owner can change settings.</p> }</main>` })
export class ProjectSettingsComponent {
  private api = inject(ApiService); private route = inject(ActivatedRoute); private router = inject(Router); readonly inspection = inject(InspectionService); readonly project = signal<Project | undefined>(undefined); readonly members = signal<Member[]>([]); readonly directory = signal<Person[]>([]); readonly error = signal(''); readonly defaultColor = '#80643d';
  readonly form = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: Validators.required }), description: new FormControl('', { nonNullable: true }), color: new FormControl(this.defaultColor, { nonNullable: true }), tasks_enabled: new FormControl(true, { nonNullable: true }), notes_enabled: new FormControl(false, { nonNullable: true }) }); readonly memberForm = new FormGroup({ username: new FormControl('', { nonNullable: true, validators: Validators.required }) });
  constructor() { void this.load(); } key() { return this.route.snapshot.paramMap.get('key')!; } owner() { return this.project()?.role === 'OWNER'; } available() { return this.directory().filter(p => !this.members().some(m => m.username === p.username)); }
  async load() { try { const key = this.key(); const projects = await this.api.request<Project[]>(`/api/projects?inspection=${this.inspection.active()}&include_archived=true`); const project = projects.find(p => p.key === key); this.project.set(project); if (!project) return; this.form.reset({ name: project.name, description: project.description, color: project.color || this.defaultColor, tasks_enabled: project.tasks_enabled, notes_enabled: project.notes_enabled }); if (this.owner()) { this.members.set(await this.api.request<Member[]>(`/api/projects/${key}/members`)); this.directory.set(await this.api.request<Person[]>('/api/directory')); } } catch (e) { this.error.set(e instanceof Error ? e.message : 'Request failed'); } }
  async save() { if (this.form.invalid || this.inspection.active()) return; await this.run(() => { const v = this.form.getRawValue(); return this.api.request(`/api/projects/${this.key()}`, { method: 'PATCH', body: { ...v, color: v.color === this.defaultColor ? null : v.color } }); }); }
  async archive() { const p = this.project(); if (p && !this.inspection.active()) await this.run(() => this.api.request(`/api/projects/${p.key}`, { method: 'PATCH', body: { archived: !p.archived } })); }
  async addMember() { if (this.memberForm.invalid) return; await this.run(() => this.api.request(`/api/projects/${this.key()}/members`, { method: 'POST', body: this.memberForm.getRawValue() })); }
  async remove(username: string) { await this.run(() => this.api.request(`/api/projects/${this.key()}/members/${username}`, { method: 'DELETE' })); }
  async transfer(username: string) { await this.run(async () => { await this.api.request(`/api/projects/${this.key()}/transfer-owner`, { method: 'POST', body: { username } }); await this.router.navigateByUrl('/projects'); }); }
  private async run(action: () => Promise<unknown>) { try { await action(); await this.load(); } catch (e) { this.error.set(e instanceof Error ? e.message : 'Request failed'); } }
}
