import { DatePipe, NgStyle } from '@angular/common';
import { Component, effect, inject, signal } from '@angular/core';
import { AbstractControl, FormControl, FormGroup, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { InspectionService } from '../core/inspection.service';
import { Project, Tag, TagProposal } from '../models';
import { HeaderComponent } from '../shared/header.component';
import { tagStyle } from '../shared/tag-colors';

@Component({ imports: [DatePipe, NgStyle, ReactiveFormsModule, RouterLink, HeaderComponent], template: `
<main><app-header /><nav><a [routerLink]="['/projects', key(), 'tasks']">← Tasks</a></nav><h2>Manage tags</h2><p class="error">{{ error() }}</p>
@if (writable()) { <section class="card"><h3>{{ editing() ? 'Edit tag' : 'Create tag' }}</h3><form [formGroup]="form" (ngSubmit)="save()"><label>Tag name<input formControlName="name" maxlength="64" [readonly]="!!editing() && !owner()"><small class="form-help">Lowercase slug: letters, numbers, and single hyphens.</small></label>@if (form.controls.name.invalid && form.controls.name.touched) { <p class="field-error">Enter a lowercase slug of at most 64 characters.</p> }<label>Color<input formControlName="color" type="color"></label><label>Description<textarea formControlName="description" maxlength="500"></textarea></label>@if (form.controls.description.invalid && form.controls.description.touched) { <p class="field-error">Description must be at most 500 characters.</p> }<button [disabled]="form.invalid">{{ editing() ? 'Save tag' : 'Create tag' }}</button>@if (editing()) { <button type="button" class="quiet" (click)="cancelEdit()">Cancel</button> }</form></section> }
<section class="task-list">@for (tag of tags(); track tag.id) { <article class="task"><span class="tag-chip" [ngStyle]="style(tag.color)">{{ tag.name }}</span><span>{{ tag.description || 'No description' }}</span><small>{{ tag.usage_count }} task{{ tag.usage_count === 1 ? '' : 's' }} · {{ tag.archived_at ? 'Archived' : 'Active' }} · created by {{ tag.creator || 'Unknown' }}</small>@if (writable()) { <span><button class="quiet" (click)="edit(tag)">Edit</button>@if (owner() && !tag.archived_at) { <button class="danger" (click)="archive(tag)">Archive</button> }</span> }</article> }</section>
<section class="card"><h3>Pending agent proposals</h3>@if (reviewing()) { <form [formGroup]="proposalForm" (ngSubmit)="approve()"><label>Name<input formControlName="name" maxlength="64"><small class="form-help">Lowercase slug: letters, numbers, and single hyphens.</small></label>@if (proposalForm.controls.name.invalid && proposalForm.controls.name.touched) { <p class="field-error">Enter a lowercase slug of at most 64 characters.</p> }<label>Color<input formControlName="color" type="color"></label><label>Description<textarea formControlName="description" maxlength="500"></textarea></label>@if (proposalForm.controls.description.invalid && proposalForm.controls.description.touched) { <p class="field-error">Description must be at most 500 characters.</p> }<label class="toggle"><input formControlName="apply_requested_tasks" type="checkbox"> Apply to requested tasks</label><button [disabled]="proposalForm.invalid || !writable()">Approve</button><button type="button" class="quiet" (click)="reviewing.set(undefined)">Cancel</button></form> }@for (proposal of proposals(); track proposal.id) { <article class="task"><span>{{ proposal.name }}</span><span>{{ proposal.description || 'No description' }}</span><small>Requested by {{ proposal.proposed_by || 'Unknown' }} · expires {{ proposal.expires_at | date:'medium' }}</small>@if (writable()) { <span><button class="quiet" (click)="review(proposal)">Review</button><button class="danger" (click)="rejectProposal(proposal)">Reject</button></span> }</article> }</section>
</main>` })
export class TagManagementComponent {
  private api = inject(ApiService); private route = inject(ActivatedRoute); readonly inspection = inject(InspectionService); readonly project = signal<Project | undefined>(undefined); readonly tags = signal<Tag[]>([]); readonly proposals = signal<TagProposal[]>([]); readonly editing = signal<Tag | undefined>(undefined); readonly reviewing = signal<TagProposal | undefined>(undefined); readonly error = signal('');
  readonly form = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: tagNameValidator }), color: new FormControl('#80643d', { nonNullable: true, validators: Validators.required }), description: new FormControl('', { nonNullable: true, validators: trimmedMaxLength(500) }) });
  readonly proposalForm = new FormGroup({ name: new FormControl('', { nonNullable: true, validators: tagNameValidator }), color: new FormControl('#80643d', { nonNullable: true, validators: Validators.required }), description: new FormControl('', { nonNullable: true, validators: trimmedMaxLength(500) }), apply_requested_tasks: new FormControl(true, { nonNullable: true }) });
  constructor() { effect(() => { this.inspection.active(); void this.load(); }); this.route.paramMap.subscribe(() => void this.load()); }
  key() { return this.route.snapshot.paramMap.get('key')!; } owner() { return this.project()?.role === 'OWNER'; } writable() { return !!this.project()?.role && !this.project()?.archived && !this.inspection.active(); } style(color: string) { return tagStyle(color); }
  async load() { try { const inspection = this.inspection.active(), key = this.key(), projects = await this.api.request<Project[]>(`/api/projects?inspection=${inspection}&include_archived=true`); this.project.set(projects.find(project => project.key === key)); const [tags, proposals] = await Promise.all([this.api.request<Tag[]>(`/api/projects/${encodeURIComponent(key)}/tags?include_archived=true&inspection=${inspection}`), this.api.request<TagProposal[]>(`/api/tag-proposals?project=${encodeURIComponent(key)}&status=PENDING&inspection=${inspection}`)]); this.tags.set(tags); this.proposals.set(proposals); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Request failed'); } }
  edit(tag: Tag) { this.editing.set(tag); this.form.reset({ name: tag.name, color: tag.color, description: tag.description }); } cancelEdit() { this.editing.set(undefined); this.form.reset({ name: '', color: '#80643d', description: '' }); }
  async save() { const value = normalize(this.form.getRawValue()); this.form.patchValue(value); if (this.form.invalid) { this.form.markAllAsTouched(); return; } await this.run(async () => { const tag = this.editing(); if (tag) await this.api.request(`/api/tags/${tag.id}`, { method: 'PATCH', body: this.owner() ? value : { color: value.color, description: value.description } }); else await this.api.request(`/api/projects/${this.key()}/tags`, { method: 'POST', body: value }); this.cancelEdit(); }); }
  async archive(tag: Tag) { await this.run(() => this.api.request(`/api/tags/${tag.id}/archive`, { method: 'POST' })); } review(proposal: TagProposal) { this.reviewing.set(proposal); this.proposalForm.reset({ name: proposal.name, color: proposal.color, description: proposal.description, apply_requested_tasks: true }); }
  async approve() { const proposal = this.reviewing(), value = normalize(this.proposalForm.getRawValue()); this.proposalForm.patchValue(value); if (!proposal || this.proposalForm.invalid) { this.proposalForm.markAllAsTouched(); return; } await this.run(async () => { await this.api.request(`/api/tag-proposals/${proposal.id}/approve`, { method: 'POST', body: value }); this.reviewing.set(undefined); }); }
  async rejectProposal(proposal: TagProposal) { await this.run(async () => { await this.api.request(`/api/tag-proposals/${proposal.id}/reject`, { method: 'POST' }); this.reviewing.set(undefined); }); }
  private async run(action: () => Promise<unknown>) { try { await action(); await this.load(); } catch (error) { this.error.set(error instanceof Error ? error.message : 'Request failed'); } }
}

function normalize<T extends { name: string; description: string }>(value: T): T { return { ...value, name: value.name.trim().toLowerCase(), description: value.description.trim() }; }
function tagNameValidator(control: AbstractControl): ValidationErrors | null { const value = String(control.value).trim().toLowerCase(); return value.length <= 64 && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) ? null : { tagName: true }; }
function trimmedMaxLength(max: number) { return (control: AbstractControl): ValidationErrors | null => String(control.value).trim().length <= max ? null : { maxlength: { requiredLength: max, actualLength: String(control.value).trim().length } }; }
