import { expect, test, type Page, type Response } from '@playwright/test';

const temporaryPassword = 'e2e-temporary-password';
const password = 'e2e-changed-password';

async function signIn(page: Page, value = password) {
  await page.getByLabel('Username').fill('e2e-admin');
  await page.getByLabel('Password').fill(value);
  await page.getByRole('button', { name: 'Sign in' }).click();
}

async function expectSession(page: Page) {
  await expect.poll(async () => (await page.request.get('/api/auth/me')).status()).toBe(200);
}

async function loginReady(page: Page) {
  await page.goto('/home');
  await signIn(page);
  await expect(page).toHaveURL(/\/home$/);
  await expectSession(page);
}

async function createProject(page: Page, key: string, name: string, tasks: boolean, notes: boolean) {
  const responses: Response[] = [];
  page.on('response', response => responses.push(response));
  await page.getByRole('button', { name: 'New project' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Key').fill(key);
  await dialog.getByLabel('Name').fill(name);
  const tasksControl = dialog.getByLabel('Tasks');
  const notesControl = dialog.getByLabel('Notes');
  if (await tasksControl.isChecked() !== tasks) await tasksControl.click();
  if (await notesControl.isChecked() !== notes) await notesControl.click();
  const post = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/projects');
  await dialog.getByRole('button', { name: 'Create' }).click();
  const response = await post;
  expect(response.request().postDataJSON()).toMatchObject({ key, name, tasks_enabled: tasks, notes_enabled: notes });
  expect(await response.json()).toMatchObject({ key, tasks_enabled: tasks, notes_enabled: notes });
  await expect(page).toHaveURL(new RegExp(`/projects/${key}/${tasks ? 'tasks' : 'notes'}$`));
  const projectGets = () => responses.slice(responses.indexOf(response) + 1).filter(item => item.request().method() === 'GET' && new URL(item.url()).pathname === '/api/projects');
  await expect.poll(() => projectGets().length).toBeGreaterThan(0);
  expect(await projectGets()[0].json()).toEqual(expect.arrayContaining([expect.objectContaining({ key, tasks_enabled: tasks, notes_enabled: notes })]));
}

test.describe.configure({ mode: 'serial' });

test('keeps a Notes-only project on Notes through reload and re-login', async ({ page }) => {
  await page.goto('/home');
  await signIn(page, temporaryPassword);
  await expect(page).toHaveURL(/\/home$/);
  await expectSession(page);
  await page.goto('/password-change?returnUrl=%2Fhome');
  await page.getByLabel('Temporary password').fill(temporaryPassword);
  await page.getByLabel('New password').fill(password);
  await page.getByRole('button', { name: 'Change password' }).click();
  await expect(page).toHaveURL(/\/login/);
  await signIn(page);
  await expect(page).toHaveURL(/\/home$/);
  await expectSession(page);

  await createProject(page, 'e2e-notes', 'E2E Notes', false, true);
  const notesUrl = '/projects/e2e-notes/notes';
  await expect(page.getByRole('heading', { name: 'Notes' })).toBeVisible();
   await expect(page.getByRole('button', { name: 'Collapse E2E Notes' })).toHaveAttribute('aria-expanded', 'true');
   await page.getByLabel('Add to project root').click();
   await expect(page.getByRole('button', { name: 'New note' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Add Todo' })).toHaveCount(0);
  expect((await page.context().cookies()).some(cookie => cookie.name === 'taskrelay_session')).toBe(true);
  const me = page.waitForResponse(response => new URL(response.url()).pathname === '/api/auth/me');
  await page.reload();
  expect((await me).status()).toBe(200);
  await expect(page).toHaveURL(notesUrl);
  await expect(page.getByRole('heading', { name: 'Notes' })).toBeVisible();

   page.once('dialog', dialog => dialog.accept('E2E folder'));
   await page.getByLabel('Add to project root').click();
   await page.getByRole('button', { name: 'New folder' }).click();
    await expect(page.getByText('E2E folder', { exact: true })).toBeVisible();
   let notePosts = 0;
   page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/projects/e2e-notes/notes') notePosts++; });
    const folderAdd = page.getByLabel('Add to E2E folder');
    await folderAdd.click();
     await page.locator('.folder-tree').filter({ has: folderAdd }).getByRole('button', { name: 'New note' }).click();
    await expect(page).toHaveURL(/\/projects\/e2e-notes\/notes\/new\?folder_id=\d+$/);
    expect(notePosts).toBe(0);
    await expect(page.locator('select[formcontrolname="folder_id"]')).toHaveValue(/\d+/);
   await page.getByRole('button', { name: 'Cancel' }).click();
   await expect(page).toHaveURL(notesUrl);
   expect(notePosts).toBe(0);
    await folderAdd.click();
     await page.locator('.folder-tree').filter({ has: folderAdd }).getByRole('button', { name: 'New note' }).click();
  await page.getByRole('textbox', { name: 'Title', exact: true }).fill('E2E note');
  await page.getByLabel('Markdown', { exact: true }).fill('# E2E preview');
   await page.getByRole('button', { name: 'Save' }).click();
   await expect(page).toHaveURL(/\/projects\/e2e-notes\/notes\/\d+$/);
   expect(notePosts).toBe(1);
     await expect(page.getByRole('heading', { name: 'Preview', exact: true })).toHaveCount(0);
      await expect(page.getByRole('heading', { name: 'E2E preview' })).toBeVisible();
       await expect(page.getByLabel('Markdown', { exact: true })).toHaveCount(0);
      await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toHaveAttribute('aria-current', 'page');
      const selectedNote = page.getByRole('link', { name: 'E2E note', exact: true }).locator('..');
      await expect(selectedNote.locator('.tree-note-marker')).toHaveAttribute('aria-hidden', 'true');
      await expect.poll(() => selectedNote.evaluate(element => ({ background: getComputedStyle(element).backgroundColor, indicator: getComputedStyle(element).boxShadow }))).toEqual(expect.objectContaining({ background: expect.not.stringMatching(/rgba\(0, 0, 0, 0\)|transparent/), indicator: expect.not.stringMatching(/^none$/) }));
     const noteMove = page.waitForResponse(response => response.request().method() === 'PATCH' && new URL(response.url()).pathname.match(/^\/api\/notes\/\d+$/) !== null);
      await page.getByTitle('Drag E2E note').dragTo(page.locator('.project-note-tree > .project-tree-row'));
    expect((await noteMove).request().postDataJSON()).toMatchObject({ title: 'E2E note', markdown: '# E2E preview', folder_id: null, expected_version: expect.any(Number) });
     await expect(page.locator('.project-note-tree > .tree-children > .note-tree-row > .note-tree').filter({ hasText: 'E2E note' })).toHaveCount(1);
    await expect(page.locator('.note-tree').filter({ hasText: 'E2E note' })).toHaveCount(1);
     const noteReturn = page.waitForResponse(response => response.request().method() === 'PATCH' && new URL(response.url()).pathname.match(/^\/api\/notes\/\d+$/) !== null);
      await page.getByTitle('Drag E2E note').dragTo(page.locator('.folder-tree').filter({ hasText: 'E2E folder' }));
    await noteReturn;
      await expect(page.locator('.folder-tree > .tree-children > .note-tree-row > .note-tree').filter({ hasText: 'E2E note' })).toHaveCount(1);
     const folderToggle = page.getByRole('button', { name: 'Collapse E2E folder' });
     await folderToggle.click();
     await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toHaveCount(0);
     await expect(page.getByRole('button', { name: 'Expand E2E folder' })).toBeVisible();
     await page.getByRole('button', { name: 'Expand E2E folder' }).click();
     await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toBeVisible();
     await folderAdd.click();
     const panel = page.locator('.folder-tree .tree-action-panel'), noteLink = page.getByRole('link', { name: 'E2E note', exact: true });
      expect((await panel.boundingBox())!.y + (await panel.boundingBox())!.height).toBeLessThanOrEqual((await noteLink.boundingBox())!.y);
       expect((await panel.boundingBox())!.height).toBeLessThanOrEqual(70);
      await folderAdd.click();
      page.once('dialog', dialog => dialog.accept('E2E nested folder'));
      await folderAdd.click();
      await page.locator('.folder-tree').filter({ has: folderAdd }).getByRole('button', { name: 'New folder' }).click();
      const rootFolder = page.locator('.folder-tree').filter({ has: folderAdd });
      const nestedFolder = page.locator('.folder-tree > .tree-row').filter({ hasText: 'E2E nested folder' }).locator('..');
      expect((await nestedFolder.locator('> .tree-row .tree-name').boundingBox())!.x).toBeGreaterThanOrEqual((await rootFolder.locator('> .tree-row .tree-name').boundingBox())!.x + 12);
      await page.getByTitle('Drag E2E note').dragTo(nestedFolder);
      await expect(nestedFolder.locator('.tree-note-marker')).toHaveAttribute('aria-hidden', 'true');
    await page.reload();
     await expect(page.getByLabel('Markdown', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Edit' }).focus();
    await page.keyboard.press('Enter');
    const folderSelect = page.getByRole('combobox', { name: 'Folder', exact: true });
    await expect(folderSelect).toBeVisible();
    await folderSelect.focus();
    await expect(folderSelect).toBeFocused();
     await page.getByLabel('Markdown', { exact: true }).fill('# Changed preview');
   page.once('dialog', dialog => dialog.dismiss());
   await page.getByRole('button', { name: 'Cancel' }).click();
    await expect(page.getByLabel('Markdown', { exact: true })).toBeVisible();
   page.once('dialog', dialog => dialog.accept());
   await page.getByRole('button', { name: 'Cancel' }).click();
    await expect(page.getByLabel('Markdown', { exact: true })).toHaveCount(0);
   await page.getByRole('button', { name: 'Edit' }).click();
   await page.getByLabel('Markdown', { exact: true }).fill('# Saved preview');
    await page.getByRole('button', { name: 'Save' }).click();
    await expect(page.getByLabel('Markdown', { exact: true })).toHaveCount(0);

    let parentName = 'E2E nested folder';
    for (let depth = 1; depth <= 3; depth++) {
      const parent = page.locator('.folder-tree > .tree-row').filter({ hasText: parentName }).locator('..');
      await parent.getByLabel(`Add to ${parentName}`).click();
      page.once('dialog', dialog => dialog.accept(`E2E deep ${depth}`));
      await parent.locator('> .tree-action-panel').getByRole('button', { name: 'New folder' }).click();
      parentName = `E2E deep ${depth}`;
    }
    await page.setViewportSize({ width: 390, height: 844 });
    const foldersPane = page.locator('.folders');
    expect(await foldersPane.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    const deepestFolder = page.locator('.folder-tree > .tree-row').filter({ hasText: 'E2E deep 3' }).locator('..');
    const deepestAdd = deepestFolder.getByLabel('Add to E2E deep 3');
    await deepestAdd.scrollIntoViewIfNeeded();
    await expect(deepestAdd).toBeVisible();
    await expect(deepestFolder.getByLabel('Manage E2E deep 3')).toBeVisible();
    await page.setViewportSize({ width: 1280, height: 720 });

   await page.getByRole('button', { name: 'Logout' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.goto(notesUrl);
  await expect(page).toHaveURL(/\/login/);
  await signIn(page);
  await expect(page).toHaveURL(notesUrl);
  await expectSession(page);
  await expect(page.getByRole('heading', { name: 'Notes' })).toBeVisible();
});

test('shows only enabled project capabilities on the overview', async ({ page }) => {
  await loginReady(page);
  await page.getByRole('button', { name: 'New project' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Key').fill('bad--key');
  await dialog.getByLabel('Name').fill('Validation project');
  let projectPosts = 0;
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/projects') projectPosts++; });
  await dialog.getByRole('button', { name: 'Create' }).click();
  await expect(dialog.getByText('Please correct the highlighted fields before creating the project.')).toBeVisible();
  await expect(dialog.getByText('Enter a valid project key.')).toBeVisible();
  await expect(page).toHaveURL(/\/home$/);
  expect(projectPosts).toBe(0);
  const projectPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/projects');
  await dialog.getByLabel('Key').fill('e2e-validation');
  await dialog.getByRole('button', { name: 'Create' }).click();
  expect((await projectPost).status()).toBe(201);
  await expect(page).toHaveURL('/projects/e2e-validation/tasks');
  await page.goto('/home');

  await createProject(page, 'e2e-tasks', 'E2E Tasks', true, false);
  await page.goto('/home');
  await createProject(page, 'e2e-both', 'E2E Both', true, true);
  await page.goto('/home');

  const tasksOnly = page.getByRole('article').filter({ hasText: 'E2E Tasks' });
  const notesOnly = page.getByRole('article').filter({ hasText: 'E2E Notes' });
  const combined = page.getByRole('article').filter({ hasText: 'E2E Both' });
  await expect(tasksOnly.locator('.home-capabilities')).toHaveCSS('grid-template-columns', /1fr 1fr|.*px.*px/);
  await expect(tasksOnly.getByText('Notes · Off')).toHaveAttribute('aria-disabled', 'true');
  await expect(notesOnly.getByText('Tasks · Off')).toHaveAttribute('aria-disabled', 'true');
  await expect(combined.getByRole('link', { name: /Tasks · 0 open \/ 0 done/ })).toBeVisible();
  await expect(combined.getByRole('link', { name: /Notes · 0/ })).toBeVisible();

  await tasksOnly.locator('.home-capabilities').getByRole('link', { name: /Tasks/ }).click();
  await expect(page).toHaveURL('/projects/e2e-tasks/tasks');
  await expect(page.getByRole('heading', { name: 'E2E Tasks' })).toBeVisible();
  await page.goto('/home');
  await notesOnly.locator('.home-capabilities').getByRole('link', { name: /Notes/ }).click();
  await expect(page).toHaveURL('/projects/e2e-notes/notes');
  await expect(page.getByRole('heading', { name: 'Notes' })).toBeVisible();
  await page.goto('/home');
  await combined.locator('.home-capabilities').getByRole('link', { name: /Tasks/ }).click();
  await expect(page).toHaveURL('/projects/e2e-both/tasks');
  await expect(page.getByRole('heading', { name: 'E2E Both' })).toBeVisible();
  await page.goto('/home');
  await combined.locator('.home-capabilities').getByRole('link', { name: /Notes/ }).click();
  await expect(page).toHaveURL('/projects/e2e-both/notes');
  await expect(page.getByRole('heading', { name: 'Notes' })).toBeVisible();
});

test('uses Home primary navigation and keeps global task filters in the URL', async ({ page }) => {
  await loginReady(page);
  await page.goto('/projects');
  await expect(page).toHaveURL('/home');
  const sidebar = page.locator('aside');
  await sidebar.getByRole('link', { name: 'Home', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible();
  await sidebar.getByRole('link', { name: 'Tasks', exact: true }).first().click();
  await expect(page).toHaveURL('/tasks');
  await sidebar.getByRole('link', { name: 'Notes', exact: true }).first().click();
  await expect(page).toHaveURL('/notes');

  await page.goto('/projects/e2e-tasks/tags');
  await page.getByLabel('Tag name').fill('unknown arbitrary');
  await expect(page.getByRole('button', { name: 'Create tag' })).toBeDisabled();
  await page.getByLabel('Tag name').fill('focus');
  await page.getByLabel('Color').fill('#336699');
  await page.getByLabel('Description').fill('Needs attention');
  const tagPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/projects/e2e-tasks/tags');
  await page.getByRole('button', { name: 'Create tag' }).click();
  expect((await tagPost).request().postDataJSON()).toEqual({ name: 'focus', color: '#336699', description: 'Needs attention' });
  await page.getByLabel('Tag name').fill('retired');
  await page.getByRole('button', { name: 'Create tag' }).click();
  const retired = page.getByRole('article').filter({ hasText: 'retired' });
  await retired.getByRole('button', { name: 'Edit' }).click();
  await page.getByLabel('Tag name').fill('retired-old');
  await page.getByRole('button', { name: 'Save tag' }).click();
  await page.getByRole('article').filter({ hasText: 'retired-old' }).getByRole('button', { name: 'Archive' }).click();
  await page.getByRole('link', { name: '← Tasks' }).click();
  await page.getByRole('button', { name: 'New task' }).click();
  const newTask = page.getByRole('dialog', { name: 'New task' });
  await newTask.getByLabel('Title').fill('E2E urgent focus');
  await newTask.getByLabel('Priority').selectOption('URGENT');
  await newTask.getByRole('button', { name: 'focus' }).click();
  const taskPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/tasks');
  await newTask.getByRole('button', { name: 'Create task' }).click();
  await expect(taskPost.then(response => response.request().postDataJSON())).resolves.toMatchObject({ tag_ids: [expect.any(Number)] });
  await page.goto('/home');
  const taskCard = page.getByRole('article').filter({ hasText: 'E2E Tasks' });
  const preview = taskCard.locator('.task-previews a').filter({ hasText: 'E2E urgent focus' });
  await expect(preview).toBeVisible();
  await expect(taskCard.locator('.activity')).toContainText('created task');
  await expect(taskCard.locator('.activity')).toContainText('E2E urgent focus');
  const activityText = (await taskCard.locator('.activity').textContent())!.replace(/\s+/g, ' ').trim();
  expect(activityText).not.toContain('vor');
  expect(activityText).toMatch(/^.+ created task “E2E urgent focus” · .+ ago$/);
  await preview.click();
   await expect(page).toHaveURL(/\/projects\/e2e-tasks\/tasks\/\d+$/);
   await expect(page.getByRole('dialog', { name: 'Task details' })).toBeVisible();
   await expect(page.getByRole('dialog', { name: 'Task details' }).getByText('TODO', { exact: true })).toBeVisible();
   await expect(page.getByRole('dialog', { name: 'Task details' }).locator('time')).toHaveCount(2);
  await page.getByRole('button', { name: 'Close task details' }).click();
  await expect(page).toHaveURL('/projects/e2e-tasks/tasks');
  await page.goBack();
  await expect(page.getByRole('dialog', { name: 'Task details' })).toBeVisible();
  await page.goto('/home');
  const noteCard = page.getByRole('article').filter({ hasText: 'E2E Notes' });
  await expect(noteCard.getByText('Recently updated note')).toBeVisible();
  await expect(noteCard.getByText(/Edited by /)).toBeVisible();
  await expect(noteCard.getByText('E2E folder')).toBeVisible();
  await noteCard.locator('.recent-note').click();
  await expect(page).toHaveURL(/\/notes\/\d+$/);
  await page.goto('/projects/e2e-both/tasks');
  await page.getByRole('button', { name: 'New task' }).click();
  const otherTask = page.getByRole('dialog', { name: 'New task' });
  await otherTask.getByLabel('Title').fill('E2E low other');
  await otherTask.getByLabel('Priority').selectOption('LOW');
  await otherTask.getByRole('button', { name: 'Create task' }).click();
  await page.goto('/tasks');
  await expect(page.getByText('E2E urgent focus')).toBeVisible();
  await expect(page.getByText('E2E low other')).toBeVisible();
  const filterBody = page.locator('#task-filter-body'), filterText = page.locator('.filter-text'), filterSort = page.locator('.filter-sort');
  expect((await filterBody.boundingBox())!.height).toBeLessThanOrEqual(80);
  expect(Math.abs((await filterText.boundingBox())!.y - (await filterSort.boundingBox())!.y)).toBeLessThanOrEqual(5);
  await page.setViewportSize({ width: 701, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await page.locator('.filter-text input').boundingBox())!.width).toBeGreaterThan(80);
  expect((await page.locator('.filter-status select').boundingBox())!.width).toBeGreaterThan(80);
  await page.goto('/projects/e2e-tasks/tasks');
  await expect(page.getByText('E2E urgent focus')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await page.locator('.filter-text input').boundingBox())!.width).toBeGreaterThan(80);
  expect((await page.locator('.filter-status select').boundingBox())!.width).toBeGreaterThan(70);
  await page.goto('/tasks');
  await page.setViewportSize({ width: 1151, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await filterBody.boundingBox())!.height).toBeLessThanOrEqual(80);
  expect(Math.abs((await filterText.boundingBox())!.y - (await filterSort.boundingBox())!.y)).toBeLessThanOrEqual(5);
  expect((await page.locator('.filter-text input').boundingBox())!.width).toBeGreaterThan(80);
  await page.goto('/projects/e2e-tasks/tasks');
  await expect(page.getByText('E2E urgent focus')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await page.locator('.filter-text input').boundingBox())!.width).toBeGreaterThan(80);
  expect((await page.locator('.filter-status select').boundingBox())!.width).toBeGreaterThan(70);
  await page.goto('/tasks');
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByLabel(/^Project/).selectOption('e2e-tasks');
  await page.getByLabel(/^Status/).selectOption('TODO');
  await page.getByRole('combobox', { name: 'Priority' }).selectOption('URGENT');
  await page.getByLabel(/^Assignment/).selectOption('unassigned');
  await page.getByLabel(/^Text/).fill('urgent');
  await page.getByLabel(/^Sort/).selectOption('priority');
  await page.getByRole('button', { name: 'Apply' }).click();
  const focusChip = page.getByRole('article').filter({ hasText: 'E2E urgent focus' }).getByRole('button', { name: 'focus', exact: true });
  await expect(focusChip).toHaveCSS('background-color', 'rgb(51, 102, 153)');
  await expect(page.getByRole('article').filter({ hasText: 'E2E urgent focus' }).getByRole('group', { name: 'Priority: URGENT' }).locator('.priority-bar')).toHaveCSS('background-color', 'rgb(180, 35, 24)');
  await focusChip.click();
  await expect(page).toHaveURL(/project=e2e-tasks.*status=TODO.*priority=URGENT.*assignment=unassigned.*tag=\d+.*q=urgent|q=urgent.*project=e2e-tasks/);
  await expect(page.getByText('E2E urgent focus')).toBeVisible();
  await expect(page.getByText('E2E low other')).toHaveCount(0);
  await page.getByLabel(/^Sort/).selectOption('newest');
  await page.getByRole('button', { name: 'Apply' }).click();
  await expect(page).toHaveURL(/sort=newest/);
  await page.reload();
  await expect(page.getByLabel(/^Sort/)).toHaveValue('newest');
  await expect(page).not.toHaveURL(/tag=/);
  await expect(page.getByText('E2E urgent focus')).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/tag=\d+/);
});

test('shows a global read-only Notes tree and project editor link', async ({ page }) => {
  await loginReady(page);
  await page.goto('/notes');
  await expect(page.getByRole('button', { name: 'Collapse E2E Notes' })).toBeVisible();
  await expect(page.getByText('E2E folder', { exact: true })).toBeVisible();
  await page.getByLabel('Search').fill('no matching note');
  await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toHaveCount(0);
  await page.getByLabel('Search').fill('saved preview');
  await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'E2E note', exact: true }).click();
  await expect(page).toHaveURL(/\/notes\/\d+$/);
  await expect(page.getByRole('link', { name: 'E2E note', exact: true })).toHaveAttribute('aria-current', 'page');
   await expect(page.getByRole('heading', { name: 'Saved preview' })).toBeVisible();
   await expect(page.getByLabel('Markdown', { exact: true })).toHaveCount(0);
     await page.setViewportSize({ width: 390, height: 844 });
     expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
     expect((await page.locator('.note-reader').boundingBox())!.y).toBeLessThan((await page.locator('.folders').boundingBox())!.y);
     await expect(page.getByRole('heading', { name: 'Browse notes' })).toBeVisible();
     await page.setViewportSize({ width: 1280, height: 720 });
      await page.getByRole('link', { name: 'Edit note' }).click();
     await expect(page).toHaveURL(/\/projects\/e2e-notes\/notes\/\d+$/);
     await expect(page.getByLabel('Markdown', { exact: true })).toBeVisible();
     await expect(page.locator('.notes-layout')).toHaveClass(/is-editing/);
     await expect(page.locator('.folders')).toBeHidden();
     const workspace = page.locator('.note-edit-workspace'), editor = page.getByLabel('Markdown', { exact: true }), preview = page.locator('.note-edit-preview');
     expect((await editor.boundingBox())!.x).toBeLessThan((await preview.boundingBox())!.x);
     expect(Math.abs((await workspace.locator('form').boundingBox())!.y - (await preview.boundingBox())!.y)).toBeLessThanOrEqual(20);
     expect((await editor.boundingBox())!.width).toBeGreaterThanOrEqual(420);
     expect((await preview.boundingBox())!.width).toBeGreaterThanOrEqual(420);
     expect(await preview.evaluate(element => getComputedStyle(element).position)).toBe('sticky');
     expect(await workspace.locator('[role="toolbar"]').evaluate((toolbar, textarea) => toolbar.compareDocumentPosition(textarea as Node) & Node.DOCUMENT_POSITION_FOLLOWING, await editor.elementHandle())).toBeTruthy();
     await expect(preview.getByRole('heading', { name: 'Preview', exact: true })).toBeVisible();
     await editor.fill('bold'); await editor.selectText(); await page.getByRole('button', { name: 'Bold', exact: true }).click();
     await expect(editor).toHaveValue('**bold**'); await expect(preview.locator('strong')).toHaveText('bold');
      await editor.evaluate(element => element.setSelectionRange(element.value.length, element.value.length)); await page.getByRole('button', { name: 'Table', exact: true }).click();
      await expect(editor).toHaveValue(/\| --- \| --- \|/); await expect(preview.locator('table')).toBeVisible();
      await editor.fill('# Saved preview\n\n> Citation\n>\n> Still quoted.\n\nInline `code`.\n\n```ts\nconst example = true;\n```\n\n| Column | Value |\n| --- | --- |\n| One | Two |');
      const blockquote = preview.locator('blockquote'), inlineCode = preview.locator('p code'), pre = preview.locator('pre'), table = preview.locator('table');
       await expect(blockquote).toBeVisible();
       expect(await blockquote.evaluate(element => ({ border: parseFloat(getComputedStyle(element).borderLeftWidth), padding: parseFloat(getComputedStyle(element).paddingLeft), background: getComputedStyle(element).backgroundColor !== getComputedStyle(element.parentElement!).backgroundColor }))).toEqual({ border: 4, padding: 13.5, background: true });
       expect(await inlineCode.evaluate(element => ({ border: parseFloat(getComputedStyle(element).borderTopWidth), padding: parseFloat(getComputedStyle(element).paddingInlineStart), background: getComputedStyle(element).backgroundColor !== getComputedStyle(element.parentElement!).backgroundColor }))).toEqual({ border: 1, padding: 4.5, background: true });
       expect(await pre.evaluate(element => ({ overflowX: getComputedStyle(element).overflowX, padding: parseFloat(getComputedStyle(element).paddingTop), background: getComputedStyle(element).backgroundColor !== getComputedStyle(element.parentElement!).backgroundColor, codeBorder: getComputedStyle(element.querySelector('code')!).borderTopWidth }))).toEqual({ overflowX: 'auto', padding: 12, background: true, codeBorder: '0px' });
       expect(await table.evaluate(element => ({ display: getComputedStyle(element).display, headerBorder: parseFloat(getComputedStyle(element.querySelector('th')!).borderTopWidth), headerPadding: parseFloat(getComputedStyle(element.querySelector('th')!).paddingTop), headerBackground: getComputedStyle(element.querySelector('th')!).backgroundColor !== getComputedStyle(element).backgroundColor, cellBorder: parseFloat(getComputedStyle(element.querySelector('td')!).borderTopWidth), contained: element.closest('.note-edit-preview')!.scrollWidth >= element.scrollWidth }))).toEqual({ display: 'table', headerBorder: 1, headerPadding: 6.75, headerBackground: true, cellBorder: 1, contained: true });
      await page.setViewportSize({ width: 390, height: 844 });
      expect((await editor.boundingBox())!.y).toBeLessThan((await preview.boundingBox())!.y);
      expect(await preview.evaluate(element => getComputedStyle(element).position)).toBe('static');
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      expect(await table.evaluate(element => { const container = element.closest('.note-edit-preview')!; return container.scrollWidth > container.clientWidth && element.getBoundingClientRect().width > container.clientWidth; })).toBe(true);
      await expect(workspace.getByRole('toolbar', { name: 'Markdown formatting' }).getByRole('button', { name: 'Table', exact: true })).toBeVisible();
      expect(await page.evaluate(() => {
        const reader = document.body.appendChild(document.createElement('article'));
        reader.className = 'note-reader-body';
        reader.innerHTML = '<blockquote><p>Citation</p></blockquote><p>Inline <code>code</code>.</p><pre><code>const example = true;</code></pre><table><thead><tr><th>Column</th></tr></thead><tbody><tr><td>Value</td></tr></tbody></table>';
        const blockquote = reader.querySelector('blockquote')!, code = reader.querySelector('p code')!, pre = reader.querySelector('pre')!, table = reader.querySelector('table')!;
        const styles = { blockquoteBorder: getComputedStyle(blockquote).borderLeftWidth, codeBackground: getComputedStyle(code).backgroundColor, preOverflow: getComputedStyle(pre).overflowX, preCodeBorder: getComputedStyle(pre.querySelector('code')!).borderTopWidth, tableDisplay: getComputedStyle(table).display, cellBorder: getComputedStyle(table.querySelector('td')!).borderTopWidth };
        reader.remove();
        return styles;
      })).toEqual({ blockquoteBorder: '4px', codeBackground: 'rgb(244, 240, 232)', preOverflow: 'auto', preCodeBorder: '0px', tableDisplay: 'table', cellBorder: '1px' });
});

test('keeps sidebar regions and capability slots stable', async ({ page }) => {
  await loginReady(page);
  const sidebar = page.locator('aside');
  const primary = sidebar.locator('.primary-nav');
  const projects = sidebar.locator('.my-projects');
  const utility = sidebar.locator('.utility-nav');
  expect((await primary.boundingBox())!.y).toBeLessThan((await projects.boundingBox())!.y);
  expect((await projects.evaluate(element => getComputedStyle(element).overflowY))).toMatch(/auto|scroll/);
  await expect(utility.getByRole('link', { name: 'Account' })).toBeVisible();
  await expect(utility.getByRole('link', { name: 'Admin' })).toBeVisible();
  await expect(utility.getByRole('button', { name: 'Logout' })).toBeVisible();
  const notesOnly = sidebar.locator('.sidebar-project').filter({ hasText: 'E2E Notes' });
  await expect(notesOnly.getByText('Tasks', { exact: true })).toHaveAttribute('aria-disabled', 'true');
  await expect(notesOnly.getByRole('link', { name: 'Tasks', exact: true })).toHaveCount(0);
  await expect(notesOnly.getByRole('link', { name: 'Notes', exact: true })).toBeVisible();
  const tasksOnly = sidebar.locator('.sidebar-project').filter({ hasText: 'E2E Tasks' });
  await expect(tasksOnly.getByRole('link', { name: 'Tasks', exact: true })).toBeVisible();
  await expect(tasksOnly.getByText('Notes', { exact: true })).toHaveAttribute('aria-disabled', 'true');
  const cog = notesOnly.getByRole('link', { name: 'Settings for E2E Notes' });
  expect((await cog.boundingBox())!.x).toBeGreaterThan((await notesOnly.locator('.project-title-row strong').boundingBox())!.x);
  await cog.click();
  await expect(page).toHaveURL('/projects/e2e-notes/settings');
});

test('creates a normalized non-admin user and opens owner project settings from its cog', async ({ page }) => {
  await loginReady(page);
  const sidebar = page.locator('aside');
  const cog = sidebar.getByRole('link', { name: 'Settings for E2E Notes' });
  await expect(cog).toBeVisible();
  await cog.click();
  await expect(page).toHaveURL('/projects/e2e-notes/settings');

  await sidebar.getByRole('link', { name: 'Admin' }).click();
  await expect(page).toHaveURL('/admin');
  await page.getByLabel('Username').fill('E2E.User');
  await page.getByLabel('Display name').fill('E2E User');
  await page.getByLabel('Temporary password').fill('e2e-user-temporary-password');
  const userPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/users');
  await page.getByRole('button', { name: 'Create user' }).click();
  const response = await userPost;
  expect(response.status()).toBe(201);
  expect(response.request().postDataJSON()).toMatchObject({ username: 'e2e.user', display_name: 'E2E User', is_admin: false });
  await expect(page.getByText('E2E User @e2e.user')).toBeVisible();
  await expect(page.getByLabel('Username')).toHaveValue('');
});

test('keeps navigation keyboard-accessible on desktop and closes it on live mobile resize', async ({ page }) => {
  await loginReady(page);
  const sidebar = page.locator('aside');
  await expect(sidebar).toHaveAttribute('aria-hidden', 'false');
  await expect(sidebar.getByRole('heading', { name: 'My Projects' })).toBeVisible();
  const desktopNotes = sidebar.getByRole('link', { name: 'Notes', exact: true }).first();
  await desktopNotes.focus();
  await expect(desktopNotes).toBeFocused();

  await page.setViewportSize({ width: 390, height: 844 });
  await expect(sidebar).toHaveAttribute('aria-hidden', 'true');
  await expect(sidebar).toHaveAttribute('inert', '');
  await page.getByRole('button', { name: 'Toggle navigation' }).click();
  await expect(sidebar).toHaveAttribute('aria-hidden', 'false');
  const mobileNotes = sidebar.getByRole('link', { name: 'Notes', exact: true }).first();
  await expect(mobileNotes).toBeVisible();
  await mobileNotes.click();
  await expect(page).toHaveURL(/\/notes$/);
});

test('keeps task drafts isolated from inline tags and exposes task accessibility state', async ({ page }) => {
  await loginReady(page);
  await page.goto('/projects/e2e-tasks/tasks');
  const newTask = page.getByRole('dialog', { name: 'New task' });
  await page.getByRole('button', { name: 'New task' }).click();
  await newTask.getByLabel('Title').fill('Inline tag draft');
  const description = 'Draft description '.repeat(10);
  await newTask.getByLabel('Description', { exact: true }).fill(description);
  await newTask.getByPlaceholder('Search tags').fill('inline-tag');
  await newTask.getByRole('button', { name: /Create new tag/ }).click();
  let taskPosts = 0;
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/tasks') taskPosts++; });
  const tagPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/projects/e2e-tasks/tags');
  await newTask.getByRole('button', { name: 'Create tag', exact: true }).click();
  expect((await tagPost).request().postDataJSON()).toMatchObject({ name: 'inline-tag' });
  expect(taskPosts).toBe(0);
  await expect(newTask.getByLabel('Title')).toHaveValue('Inline tag draft');
  await expect(newTask.getByLabel('Description', { exact: true })).toHaveValue(description);
  const taskPost = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/tasks');
  await newTask.getByRole('button', { name: 'Create task' }).click();
  expect((await taskPost).request().postDataJSON()).toMatchObject({ title: 'Inline tag draft', description });

   await expect(page.getByRole('dialog', { name: 'Task details' })).toBeVisible();
   const taskDrawer = page.getByRole('dialog', { name: 'Task details' });
   await expect(taskDrawer.locator('.task-drawer-badges')).toContainText('NORMAL');
   await expect(taskDrawer.locator('.task-drawer-tags .tag-chip')).toContainText('inline-tag');
   await expect(taskDrawer.getByRole('heading', { name: 'Description' })).toBeVisible();
   await expect(taskDrawer.locator('.task-drawer-times time')).toHaveCount(2);
   await page.getByRole('button', { name: 'Close task details' }).click();
  await expect(page.getByRole('button', { name: 'New task' })).toBeFocused();
  const title = page.getByRole('button', { name: /Inline tag draft/ });
  await title.focus();
  await title.click();
  await expect(page.getByRole('dialog', { name: 'Task details' })).toBeVisible();
  await page.getByRole('button', { name: 'Close task details' }).click();
  await expect(title).toBeFocused();
   const more = page.locator('button.more');
  await expect(more).toHaveAttribute('aria-expanded', 'false');
  await expect(more).toHaveAttribute('aria-controls', /^task-description-\d+$/);
   await more.click();
   await expect(more).toHaveAttribute('aria-expanded', 'true');
   await expect(more).toHaveText('Less');
   await expect(page.locator(`#${await more.getAttribute('aria-controls')}`)).toHaveAttribute('aria-expanded', 'true');
   await expect(page.getByRole('dialog', { name: 'Task details' })).toHaveCount(0);
   await page.setViewportSize({ width: 390, height: 844 });
   const filters = page.getByRole('button', { name: /Filters/ });
   await expect(filters).toHaveAttribute('aria-expanded', 'false');
   expect((await page.locator('.task-row').first().boundingBox())!.y).toBeLessThan(400);
   await filters.click(); await expect(filters).toHaveAttribute('aria-expanded', 'true');
   expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('confirms dirty task navigation once and clears tag filters verbatim', async ({ page }) => {
  await loginReady(page);
  await page.goto('/projects/e2e-tasks/tasks');
  let confirmations = 0;
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByRole('dialog', { name: 'New task' }).getByLabel('Title').fill('Unsaved back draft');
  page.once('dialog', dialog => { confirmations++; dialog.dismiss(); });
  const declinedBack = page.goBack({ timeout: 1_000 });
  await expect.poll(() => confirmations).toBe(1);
  await declinedBack.catch(() => undefined);
  await expect(page).toHaveURL('/projects/e2e-tasks/tasks');
  page.once('dialog', dialog => { confirmations++; dialog.accept(); });
  await page.goBack();
  await expect(page).toHaveURL('/home');
  expect(confirmations).toBe(2);
  await page.goto('/projects/e2e-tasks/tasks');
  await page.getByRole('button', { name: 'New task' }).click();
  await page.getByRole('dialog', { name: 'New task' }).getByLabel('Title').fill('Unsaved tags draft');
  page.once('dialog', dialog => { confirmations++; dialog.dismiss(); });
  await page.getByRole('dialog', { name: 'New task' }).getByRole('link', { name: 'Manage all tags' }).click();
  await expect(page).toHaveURL('/projects/e2e-tasks/tasks');
  expect(confirmations).toBe(3);
  page.once('dialog', dialog => { confirmations++; dialog.accept(); });
  await page.getByRole('dialog', { name: 'New task' }).getByRole('link', { name: 'Manage all tags' }).click();
  await expect(page).toHaveURL('/projects/e2e-tasks/tags');
  expect(confirmations).toBe(4);

  const tags = await (await page.request.get('/api/tags')).json();
  const focus = tags.find((tag: { name: string }) => tag.name === 'focus');
  await page.goto(`/tasks?project=e2e-tasks&tag=${focus.id}`);
  await page.getByRole('button', { name: '✓ focus', exact: true }).click();
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(page).not.toHaveURL(/tag=/);
  await page.goto(`/tasks?project=e2e-tasks&tag=${focus.id}`);
  await page.getByLabel(/^Project/).selectOption('e2e-both');
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(page).not.toHaveURL(/tag=/);
});

test('loads a direct task detail independently and rejects a mismatched project URL', async ({ page }) => {
  await loginReady(page);
  const tasks = await (await page.request.get('/api/tasks?project=e2e-tasks&limit=200')).json();
  const task = tasks.find((item: { title: string }) => item.title === 'Inline tag draft');
  const detail = page.waitForResponse(response => response.request().method() === 'GET' && new URL(response.url()).pathname === `/api/tasks/${task.id}`);
  await page.goto(`/projects/e2e-tasks/tasks/${task.id}`);
  await detail;
  await expect(page.getByRole('dialog', { name: 'Task details' })).toContainText('Inline tag draft');
  await page.goto(`/projects/e2e-both/tasks/${task.id}`);
  await expect(page.getByRole('dialog', { name: 'Task details' })).toHaveCount(0);
  await expect(page.getByText('Task not found for this project.')).toBeVisible();
  await page.goto('/projects/e2e-tasks/tasks/999999');
  await expect(page.getByRole('dialog', { name: 'Task details' })).toHaveCount(0);
  await expect(page.getByText('Task not found for this project.')).toBeVisible();
});
