import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { NgStyle } from '@angular/common';
import { Project, Task } from '../models';
import { RelativeTimePipe } from './relative-time.pipe';
import { tagStyle } from './tag-colors';

@Component({ selector: 'app-task-table', imports: [NgStyle, RelativeTimePipe], template: `<section class="task-list task-table"><header class="task-table-header" [class.with-project]="showProject"><span class="task-priority">Priority</span><span class="task-main">Task</span>@if (showProject) { <span class="task-project">Project</span> }<span class="task-assignee">Assignee</span><span class="task-tags">Tags</span><span class="task-updated">Updated</span></header>@for (task of tasks; track task.id) { <article class="task task-row" [class.done]="task.status === 'DONE'" [class.expanded]="expanded() === task.id" [attr.data-priority]="task.priority">
<span class="priority-rail task-priority" role="group" [attr.aria-label]="'Priority: ' + task.priority"><span class="priority-bar" aria-hidden="true"></span><span class="priority-label priority-label-vertical" aria-hidden="true">{{ task.priority }}</span></span><section class="task-main"><button class="task-title" [attr.data-task-id]="task.id" (click)="open.emit(task)"><strong>@if (task.status === 'DONE') { <span aria-label="Completed">✓</span> } {{ task.title }}</strong></button>@if (task.description) { <span class="description" [attr.id]="descriptionId(task.id)" [attr.aria-expanded]="expanded() === task.id">{{ task.description }}</span> } @if (long(task.description)) { <button type="button" class="quiet more" [attr.aria-expanded]="expanded() === task.id" [attr.aria-controls]="descriptionId(task.id)" (click)="toggle(task.id)">{{ expanded() === task.id ? 'Less' : 'More' }}</button> }</section>
@if (showProject) { <span class="project-tag task-project" [style.background-color]="project(task.target_project)?.color || 'var(--accent)'">{{ project(task.target_project)?.name || task.target_project }}</span> }
<span class="task-assignee">{{ task.assignee || 'Unassigned' }}</span><span class="tag-row task-tags">@for (tag of task.tags; track tag.id) { <button type="button" class="tag-chip" [ngStyle]="style(tag.color)" (click)="tagClick.emit(tag.id)">{{ tag.name }}</button> }</span><time class="task-updated" [attr.datetime]="task.updated_at" [title]="task.updated_at">{{ task.updated_at | relativeTime }}</time></article> }</section>` })
export class TaskTableComponent {
  @Input() tasks: Task[] = []; @Input() projects: Project[] = []; @Input() showProject = false; @Output() open = new EventEmitter<Task>(); @Output() tagClick = new EventEmitter<number>(); expanded = signal<number | undefined>(undefined);
  project(key: string) { return this.projects.find(item => item.key === key); } style(color: string) { return tagStyle(color); } long(description: string) { return description.trim().length > 120; } descriptionId(id: number) { return `task-description-${id}`; } toggle(id: number) { this.expanded.update(expanded => expanded === id ? undefined : id); }
}
