import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NgStyle } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Member, Project, Tag } from '../models';
import { tagStyle } from './tag-colors';

export interface TagCreateRequest { name: string; color: string; description: string; resolve: (tag?: Tag) => void; }
export function taskForm() { return new FormGroup({ title: new FormControl('', { nonNullable: true, validators: Validators.required }), description: new FormControl('', { nonNullable: true }), priority: new FormControl('NORMAL', { nonNullable: true }), target_project: new FormControl('', { nonNullable: true }), tag_ids: new FormControl<number[]>([], { nonNullable: true }), assigned_user: new FormControl('', { nonNullable: true }) }); }

@Component({ selector: 'app-task-form', imports: [NgStyle, ReactiveFormsModule], template: `<div [formGroup]="form"><label>Title<input formControlName="title" maxlength="240" required></label><label>Description<textarea formControlName="description"></textarea></label><label>Priority<select formControlName="priority"><option value="LOW">LOW</option><option value="NORMAL">NORMAL</option><option value="HIGH">HIGH</option><option value="URGENT">URGENT</option></select></label>@if (showProject) { <label>Target project<select formControlName="target_project" (change)="targetChanged.emit()">@for (project of projects; track project.key) { @if (project.role && !project.archived) { <option [value]="project.key">{{ project.name }}</option> } }</select></label> }<label>Assignee<select formControlName="assigned_user"><option value="">Unassigned</option>@for (member of members; track member.username) { <option [value]="member.username">{{ member.display_name }}</option> }</select></label><fieldset class="tag-picker"><legend>Tags</legend><label>Search tags<input [formControl]="search" placeholder="Search tags"></label>@for (tag of filteredTags; track tag.id) { <button type="button" class="tag-chip" [ngStyle]="style(tag.color)" [attr.aria-pressed]="selected(tag.id)" (click)="toggle(tag.id)">@if (selected(tag.id)) { ✓ } {{ tag.name }}</button> }@for (tag of archived; track tag.id) { <span class="tag-chip" [ngStyle]="style(tag.color)">🔒 {{ tag.name }} (archived)</span> }@if (newName) { <button type="button" (click)="creating = true">Create new tag “{{ newName }}”</button> } @else if (search.value) { <p class="form-help">Use a lowercase slug: letters, numbers, and single hyphens.</p> }<a [href]="manageTagsUrl">Manage all tags</a></fieldset>@if (creating) { <section class="card" [formGroup]="tagForm"><h3>Create tag</h3><label>Color<input formControlName="color" type="color" (keydown.enter)="createTag($event)"></label><label>Description<textarea formControlName="description" maxlength="500" (keydown.enter)="createTag($event)"></textarea></label><button type="button" [disabled]="tagForm.invalid" (click)="createTag()">Create tag</button><button type="button" class="quiet" (click)="creating = false">Cancel</button></section> }</div>` })
export class TaskFormComponent {
  @Input({ required: true }) form!: ReturnType<typeof taskForm>; @Input() tags: Tag[] = []; @Input() members: Member[] = []; @Input() projects: Project[] = []; @Input() showProject = false; @Input() manageTagsUrl = ''; @Output() targetChanged = new EventEmitter<void>(); @Output() tagCreate = new EventEmitter<TagCreateRequest>();
  readonly search = new FormControl('', { nonNullable: true }); readonly tagForm = new FormGroup({ color: new FormControl('#80643d', { nonNullable: true }), description: new FormControl('', { nonNullable: true }) }); creating = false;
  get filteredTags() { const q = this.search.value.toLowerCase(); return this.tags.filter(tag => !tag.archived_at && tag.name.includes(q)); } get archived() { return this.tags.filter(tag => !!tag.archived_at && this.selected(tag.id)); } get newName() { const name = this.search.value.trim().toLowerCase(); return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name) && !this.tags.some(tag => !tag.archived_at && tag.name === name) ? name : ''; }
  selected(id: number) { return this.form.controls.tag_ids.value.includes(id); } toggle(id: number) { const values = this.form.controls.tag_ids.value; this.form.controls.tag_ids.setValue(values.includes(id) ? values.filter(value => value !== id) : [...values, id]); } style(color: string) { return tagStyle(color); }
  async createTag(event?: Event) { event?.preventDefault(); event?.stopPropagation(); if (!this.newName || this.tagForm.invalid) return; const tag = await new Promise<Tag | undefined>(resolve => this.tagCreate.emit({ name: this.newName, ...this.tagForm.getRawValue(), resolve })); if (tag) { this.form.controls.tag_ids.setValue([...this.form.controls.tag_ids.value, tag.id]); this.search.setValue(''); this.tagForm.reset({ color: '#80643d', description: '' }); this.creating = false; } }
}
